name: Child Workflow

on:
  push:
    branches:
      - development

  workflow_dispatch:
    inputs:
      target:
        description: "Target"
        required: true
        default: "main"

jobs:
  read-target:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: read-target
        id: read-target
        run: |
          BRANCH=${{ github.ref }}
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          TARGET=${{ github.event.inputs.target }}
          echo target: $TARGET
          echo branch: $BRANCH
          echo branch-name: $BRANCH_NAME
          echo "target=$TARGET" >> $GITHUB_ENV
