name: Parent Workflow

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target"
        required: true
        default: "main"
      date:
        description: "Date"
        required: true
        default: "YYYY/MM/DD"

jobs:
  read-target:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.read-input.outputs.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read input
        id: read-input
        run: |
          TARGET=${{ github.event.inputs.target }}
          DATE=${{ github.event.inputs.date }}
          echo target: $TARGET
          echo date: $DATE
          echo "target=$TARGET" >> $GITHUB_OUTPUT

  kick-child:
    needs: read-target
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Trigger child workflow
        uses: actions/github-script@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const response = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: `child.yml`,
              ref: `${{ env.TARGET }}`,
              inputs: {
                "target": `${{ env.TARGET }}`,
              }
            });
